fix double open multiple select problem and fix tests
netdjw/ddata-core pull request #29
Opened 2022-03-07 15:57 UTC by csonti4000

2022-03-07 17:31 UTC, netdjw requested changes
- deb fájlt töröld ki, binárisnak nincs keresnivalója a git-en
- select.component.spec.ts~ fájlt töröld ki, ha nem kell

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui-input/src/lib/components/select/select.component.spec.ts
> +describe('SelectComponentMultipleSelect', () => {
nem igazán beszédes a teszt elnevezése, ide jobb lenne a komponens nevét írni

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui-input/src/lib/components/select/select.component.spec.ts
> +        component.multipleSelect = true;
nem ez a komponens lesz, ami megjelenik a multiple select listában, szóval ennek itt nincs sok értelme szerintem

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui-input/src/lib/components/select/select.component.spec.ts
> +        component.componentRef.instance.select.next([new MockModel().init({ name: 'test1' })]);
a folyamat nem igazán jól van tesztelve. Jelenleg ezt teszteled:
1. létrehozod a komponenst
2. beállítod rajta a dialogSettings mezőt
3. kinyitod a dialogot
4. a komponenshez hozzáadsz egy kijelölt elemet

Helyette ezt kellene tesztelni:
1. létrehozod a komponenst
2. beállítod rajta a dialogSettings mezőt
2.1. beállítod a dialog beállításokban, hogy melyik model-ek vannak kijelölve
3. kinyitod a dialogot (elemre kattintással, nem property állítgatással)
4. ellenőrzöd, hogy ki van-e jelölve, aminek ki kell
5. bezárod a dialogot (elemre kattintással, nem property állítgatással)
6. ellenőrzöd, hogy a megfelelő helyen a HTML-ben megjelenik-e a kiválaszott adat
7. újra kinyitod (elemre kattintással)
8. próbálod kattintással módosítani a kiválasztottakat
9. bezárod
10. ellenőrzöd, hogy a megfelelő helyen a HTML-ben megjelenik-e a kiválaszott adat

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui-input/src/lib/components/select/select.component.ts
> +    this.componentSubscription = new Subscription();
miért kell újabb subscription-t létrehozni?

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui-input/src/lib/components/textarea/textarea.component.spec.ts
> +  // it('getTitle() should return title', () => {
ezeket miért kellett kikommentezni?

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui/src/lib/ddata-ui.module.ts
> +// import { FileUploadComponent } from './components/file/file-upload/file-upload.component';
ha nem kell, töröld ki

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui/src/lib/ddata-ui.module.ts
> +// import { FileModel } from './models/file/file.model';
ha nem kell, töröld ki

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui/src/lib/models/folder/folder.interface.ts
> +  name: string;
ezt miért kellett módosítani?

2022-03-07 17:31 UTC, netdjw commented on projects/ddata-ui/src/lib/models/folder/folder.model.ts
> +// // import { BaseModel, FieldContainerInterface, ValidationRuleInterface, BaseModelInterface } from '../base-model/base-model.model';
ezt miért kellett kikommentezni?

2022-03-10 08:34 UTC, csonti4000 commented on projects/ddata-ui-input/src/lib/components/select/select.component.spec.ts
> +describe('SelectComponentMultipleSelect', () => {
kész

2022-03-10 08:37 UTC, csonti4000 commented on projects/ddata-ui-input/src/lib/components/textarea/textarea.component.spec.ts
> +  // it('getTitle() should return title', () => {
kész

2022-03-10 08:38 UTC, csonti4000 commented on projects/ddata-ui/src/lib/ddata-ui.module.ts
> +// import { FileUploadComponent } from './components/file/file-upload/file-upload.component';
kész

2022-03-10 08:39 UTC, csonti4000 commented on projects/ddata-ui/src/lib/ddata-ui.module.ts
> +// import { FileModel } from './models/file/file.model';
kész

2022-03-10 08:56 UTC, csonti4000 commented on projects/ddata-ui/src/lib/models/folder/folder.model.ts
> +// // import { BaseModel, FieldContainerInterface, ValidationRuleInterface, BaseModelInterface } from '../base-model/base-model.model';
kész

2022-03-10 09:02 UTC, netdjw approved these changes

2022-03-10 09:02 UTC, merged