feat(ui-input): add word counter and character counter
netdjw/ddata-core pull request #86
Opened 2024-06-28 11:27 UTC by daevne

2024-06-28 11:28 UTC, daevne commented
@netdjw Sajnos nem tudom, hogyan ellenőrizzem le, hogy jó-e, amit csináltam.

2024-06-28 11:29 UTC, daevne commented
Ehhez az issue-hoz tartozik:
https://github.com/Online-Ugyvitel/dcms/issues/3744

2024-07-01 06:06 UTC, daevne commented
@netdjw Van egy bug a dcms-ben, ami kapcsolódhat ehhez:
[test.bbmk.hu]: Szövegbeviteli mező végén levő karakterszámláló nem nulláz ha a mező tartalmát ürítjük #3735

2024-07-03 11:35 UTC, netdjw requested changes

2024-07-03 11:35 UTC, netdjw commented on projects/ddata-ui-input/src/lib/components/select/multiple-select/multiple-select.component.ts
> +  // }
remove is not neccessary

2024-07-03 17:44 UTC, daevne commented on projects/ddata-ui-input/src/lib/components/select/multiple-select/multiple-select.component.ts
> +  // }
deleted

2024-07-08 11:52 UTC, netdjw approved these changes

2024-07-08 11:52 UTC, merged